name: Bug report
description: When you find a bug but have no time to fix right now
title: "[Bug 🐛] "
labels: ["Bug 🐛"]
body:
  - type: dropdown
    id: error-type
    attributes:
      label: Error type
      description: the type of error that is persisting
      options:
        - Won't compile (compiler / makefile)
        - Memory (leaks / dangling pointer / double free)
        - Crash (Segmentation fault / Bus error / Abort)
        - Logic (Faulty behavior / Wrong output)
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: a brief summary of the bug

  - type: textarea
    id: to-recreate
    attributes:
      label: Steps To Reproduce
      description: how did it happen
      placeholder: |
        1.
        2.
        3.
        ...

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: describe current status of error
      options:
        - Cause found
        - Solution exists
      multiple: true
