name: 리팩터링
description: 코드 정리정돈하기
title: "[Refactor ⚙️] "
labels: ["Refactor ⚙️"]
body:
  - type: dropdown
    id: refactor-type
    attributes:
      label: 종류
      description: 개선할 부분
      multiple: true
      options:
        - 네임스페이스
        - 함수 / 클래스
        - 내부 구현
        - 기타
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 내용
      description: 해결 방법

  - type: dropdown
    id: others
    attributes:
      label: 그밖에
      description: 확인할 것들
      options:
        - 대규모 수정
        - 문서 작성 필요
      multiple: true
